AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Resources:
  GetSongsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: getSongs/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        Spotify:
          Type: Api
          Properties:
            Path: /songs
            Method: get
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts

Outputs:
  SpotifyApi:
    Description: "API Gateway endpoint URL for getSongs"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/songs?token=yourtoken"
